export const CategoryDict = {
    "amber":"Amber",
    "barley-wine":"Barley Wine",
    "belgian-ale":"Belgian Ale",
    "blond":"Blond",
    "bock":"Bock",
    "brown-ale":"Brown Ale",
    "dubbel":"Dubbel",
    "india-pale-ale":"India Pale Ale",
    "lager":"Lager",
    "pale-ale":"Pale Ale",
    "quadrupel":"Quadrupel",
    "saison":"Saison",
    "sour-beer":"Sour Beer",
    "stout":"Stout",
    "tripel":"Tripel",
    "weizen":"Weizen",
    "wit":"Wit",
    "pils": "Pils",
    "porter": "Porter",
} 