export const CategoryDict = {
    "Amber":"Amber",
    "Barley Wine":"Barley Wine",
    "Belgian Ale":"Belgian Ale",
    "Blond":"Blond",
    "Bock":"Bock",
    "Brown Ale":"Brown Ale",
    "Dubbel":"Dubbel",
    "India Pale Ale":"India Pale Ale",
    "Lager":"Lager",
    "Pale Ale":"Pale Ale",
    "Quadrupel":"Quadrupel",
    "Saison":"Saison",
    "Sour Beer":"Sour Beer",
    "Stout":"Stout",
    "Tripel":"Tripel",
    "Weizen":"Weizen",
    "Wit":"Wit",
    "Pils": "Pils",
    "Porter": "Porter",
} 