export const ADD_PRODUCT_CART = 'ADD_PRODUCT_CART'
export const DECREMENT_PRODUCT_CART = "DECREMENT_PRODUCT_CART"
export const DELETE_PRODUCT_CART = 'DELETE_PRODUCT_CART'
export const CLEAR_CART = 'CLEAR_CART'
export const ADD_PRODUCT_FAVORITES = 'ADD_PRODUCT_FAVORITES'
export const DELETE_PRODUCT_FAVORITES = "DELETE_PRODUCT_FAVORITES"